config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :admins
  resources :participants do
    member do
      get :download
      get 'pdf/print_details', to: 'pdf#print_details', as: 'print_details'

    end
  end

  resources :course_categories

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "participants#index"
end

app/models/participant.rb
class Participant < ApplicationRecord
    belongs_to :course_category , optional: true
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
include ApplicationHelper
  before_action :authenticate_user!
  before_action :set_participant, only: %i[ show edit update destroy download ]
  


  # GET /participants or /participants.json
  def index
      if params[:search_ics].present?
        @participants = Participant.where("ics_no LIKE ?", "%#{params[:search_ics]}%")
      else
        @participants = Participant.all
      end
    end

  # GET /participants/1 or /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants or /participants.json
  def create
    @participant = Participant.new(participant_params)


  # Find the maximum serial number for the current course category
  max_serial_num = Participant.where(course_category_id: @participant.course_category_id).maximum(:serial_num)

  # Set the serial number for the new participant
  @participant.serial_num = format('%03d', max_serial_num.to_i + 1)



    respond_to do |format|
      if @participant.save
        format.html { redirect_to participant_url(@participant), notice: "Participant was successfully created." }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1 or /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to participant_url(@participant), notice: "Participant was successfully updated." }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1 or /participants/1.json
  def destroy
    @participant.destroy!

    respond_to do |format|
      format.html { redirect_to participants_url, notice: "Participant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def download
    participant = Prawn::Document.new


    font_the_seasons =  Rails.root.join('app', 'assets', 'fonts', 'The Seasons Bold.ttf')
    participant.font(font_the_seasons)

    background_image_path = Rails.root.join('app', 'assets', 'images', 'cert.jpg')  
   
    # Set the desired position for the image
  desired_position = [-35, participant.bounds.height]

  desired_width = 610
  desired_height = 800

  participant.bounding_box([0, participant.cursor], width: participant.bounds.width, height: participant.bounds.height - 40, margin: 0) do
    # Place the image at the desired position without resizing it

    participant.image background_image_path, at: desired_position,
    # position: :center,
    # vposition: :center,
    width: desired_width,
    height: desired_height,
    # participant.image background_image_path, position: :center,
    # vposition: :center, at: desired_position,
    width: 600,
    height: 780
  
    end

    # participant.move_cursor_to(participant.bounds.height - 50)
    participant.move_cursor_to(participant.bounds.height)

     # Calculate the center point of the page
  center_x = participant.bounds.width / 2
  center_y = (participant.bounds.height - 50) / 2

 
    #single_day = 2

    custom_text = custom_text_helper(@participant)


    if @participant.name.length > 32
        participant.text_box @participant.name.upcase,
        at: [50, 380], 
        align: :center, 
        size: 36, 
        width: participant.bounds.width, 
        leading:-10,
        height: participant.bounds.height do
          stroke_bounds
        end
      else
        participant.text_box @participant.name.upcase,at: [50, 380], align: :center, size: 36, width: participant.bounds.width - (20 + 20), leading:-10,height: participant.bounds.height do
        transparent(0.5)  {stroke_bounds} 
        end
      end
    

    participant.text_box custom_format_ics_no(@participant.ics_no),at: [0, 290], align: :center, size: 22

    font_poppins = Rails.root.join('app', 'assets', 'fonts', 'Poppins-Medium.ttf')
    participant.font(font_poppins)

    
    # participant.text "#{@participant.course_category.name}",
    #                   align: :center,
    #                   font: participant.font(font_the_seasons),
    #                   inline_format: true

    participant.text_box custom_text, align: :center, at: [0, 240], size: 12, :character_spacing => 1
    # participant.text custom_text, align: :center, at: [0, 240], size: 12 , inline_format: true
    
    
    if @participant.serial_num.present?

      font_poppins_italic = Rails.root.join('app', 'assets', 'fonts', 'Poppins-MediumItalic.ttf')
      participant.font(font_poppins_italic)

      participant.text_box serial_number_helper(@participant.serial_num), align: :left, at: [35, 17], size: 6.7
   end
    send_data(participant.render, filename: "#{@participant.name}.pdf", type: 'application/pdf')  
  end
 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def participant_params
      params.require(:participant).permit(:name, :ics_no, :course, :course_category_id, :serial_num, :phone, :email)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_with(model: participant) do |form| %>
  <% if participant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
        <% participant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :ics_no, style: "display: block" %>
    <%= form.text_field :ics_no, id: 'limitedInput', maxlength: 12 %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>
  
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
  <%= form.label :course_category_id, 'Course', style: "display: block" %>
  <%= form.collection_select(:course_category_id, CourseCategory.all, :id, :name, prompt: 'Select a course') %>
</div>


  <div>
    <%= form.submit 'submit' %>
  </div>
<% end %>

app/views/participants/_participant.html.erb
<div id="<%= dom_id participant %>">
  <p>
    <strong>Name:</strong>
    <%= participant.name %>
  </p>

  <p>
    <strong>IC Number:</strong>
    <%= custom_format_ics_no(participant.ics_no) %>

  </p>

   <p>
    <strong>Serial Number:</strong>
    <%= participant.serial_num %>
  </p>

  <% if participant.course_category %>
  <p>Course Category: <%= participant.course_category.name %></p>
<% else %>
  <p>Course Category: N/A</p>
<% end %>
  

</div>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

  <%= render "form", participant: @participant %>

<br>

<div>
  <%= link_to "Show this participant", @participant %> |
  <%= link_to "Back to participants", participants_path %>
</div>

app/views/participants/index.html.erb
<%# form_with(url: participants_path, method: "get") do |form| %>
  <%# form.text_field :search_ics, placeholder: "Search by IC Number" %>
  <%# form.submit "Search" %>
<%# end %>


<p style="color: green"><%= notice %></p>

<h1>Participants</h1>

<div id="participants">
  <% @participants.each do |participant| %>
    <%= render participant %>
    <p>
      <%= link_to "Show this participant", participant %> | <%= link_to "Download" , download_participant_path(participant) %>
    </p>
  <% end %>
</div>

<%= link_to "New participant", new_participant_path %>

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render "form", participant: @participant %>

<br>

<script>
  document.getElementById('limitedInput').addEventListener('input', function() {
    if (this.value.length > 12) {
      this.value = this.value.slice(0, 12);
     }
    }
  });
</script>

<div>
  <%= link_to "Back to participants", participants_path %>
</div>

app/views/participants/show.html.erb
<p style="color: green"><%= notice %></p>

  <%= render @participant %>

<div>

  <%= link_to "Edit this participant", edit_participant_path(@participant) %> |
  <%= link_to "Back to participants", participants_path %>

  <%= button_to "Destroy this participant", @participant, method: :delete %>
  <%# link_to 'Print Details', print_details_participant_path, class: 'btn btn-primary' %>